### ISSUE TITLE
No dist folder

### ISSUE THREAD

**Issue by stop5** [Explosion-Scratch/firebuilder#1]
Currently there is no dist folder. can you upload them to the releases or update your readme?

**Comment by Explosion-Scratch** [comment]
@stop5 Sorry - Didn't realize it was gitignored! Pushing now

**Comment by Explosion-Scratch** [comment]
It is taking foreverrr I am on a slow wifi - I got darwin-arm64 uploaded on releases but the others are still going. Any specific binary you want me to prioritize?
