### ISSUE TITLE
Allow importing of more stuff from an existing profile

### ISSUE THREAD

**Issue by gotlougit** [Explosion-Scratch/firebuilder#3]
Not sure how possible this would be, but it would be nice to allow importing more stuff from an existing Firefox profile in addition to bookmarks, cookies, extensions etc.

This includes:

- userChrome.css if it is present in the profile (and other associated theming changes, like customizing the toolbar is not present right now)
- Extension configs (including their permissions and if they are enabled or not)

This would bring it to feature parity with the starting from scratch approach and would be much appreciated to create a clean config that can be backed up and restored much more easily.

**Comment by Explosion-Scratch** [comment]
Good idea - Will implement!

**Comment by Explosion-Scratch** [comment]
I couldn't figure out how to import extension configs, it kept not working when I tried but I'll give it another go.

**Comment by Explosion-Scratch** [comment]
Now you can do this:
```jsonc
{
  "extendProfile": {
    "path": "Path here"
    // Copy all existing files
    "merge": "all"
  },
}
```

Or:
```jsonc
{
    "extendProfile": {
        "path": "path/to/profile"
        "merge": ["path/in/profile/to/file.db"]
    }
}
```
