### ISSUE TITLE
Fails on startup (Ubuntu 22.04.4 LTS)

### ISSUE THREAD

**Issue by 097115** [Explosion-Scratch/firebuilder#4]
The latest binary from the Releases page says this and exits (some previous ones did something similar, too):

    > ./firebuilder-linux-x64
    ReferenceError: Can't find variable: existsSync
          at getFirefoxPaths (/$bunfs/root/firebuilder-linux-x64:24285:42)
          at /$bunfs/root/firebuilder-linux-x64:24507:50

    Bun v1.1.26 (Linux x64 baseline)

(In case it might be related, if it looks for Firefox, I have it installed locally, but a symlink is available in `/usr/bin`.)

**Comment by stop5** [comment]
I have the same issue also with 1.0.2:
```ReferenceError: Can't find variable: existsSync
at getFirefoxPaths (/$bunfs/root/firebuilder-linux-x64:24227:42)
at /$bunfs/root/firebuilder-linux-x64:24434:50

Bun v1.1.25 (Linux x64)
```

**Comment by truecelz** [comment]
Bump, I also have this issue
I was looking for something exactly like this project today, (hopefully) looking forward to using it

**Comment by Explosion-Scratch** [comment]
Fixed, sorry guys

**Comment by 097115** [comment]
@Explosion-Scratch 

Sorry, mate :)

    > ./firebuilder-linux-x64
    1 | (function (entry, fetcher)
        ^
    SyntaxError: Export named 'existsSync' not found in module 'path'.
    
    Bun v1.1.26 (Linux x64 baseline)

**Comment by stop5** [comment]
no problem, nobody is perfekt
