### ISSUE TITLE
Should outputspath be hardcoded to a user directory?

### ISSUE THREAD

**Issue by pdehaan** [Explosion-Scratch/firebuilder#5]
https://github.com/Explosion-Scratch/firebuilder/blob/89e4f75226e76a7b06977eb21be10552882cab7b/config.json#L44

although can’t tell if it’s being overridden anyways in cli.js or run.js

**Comment by Explosion-Scratch** [comment]
That doesn't really do anything, it just gets auto-generated when I test the code
