### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by demichev78** [Explosion-Scratch/firebuilder#8]
Thanks for the tool.

1. A quick suggestion. Some people from the target audience may not be familiar with bun and how to use it/install it.
2. When bun is installed on MacOs and you try to run "bun cli.js" you get error: Cannot find module "./asset-bundle" from .....cli.js
This tells me I missed some step to install dependencies.

Installation via dmg did not work as well. Even if I allow to run a binary w/o a signature it just opens the file. 

Suggestion: A more detailed installation instructions would be helpful for those who are not in NodeJS world

**Comment by Explosion-Scratch** [comment]
It's pretty simple, basically just download the correct binary for your system from the releases, then make it executable and then you can run it from terminal:
```bash
# Download the binary to your Downloads folder or something
cd ~/Downloads
# Change "firebuilder" to the name of the file. Sometimes if you type firebuilder* and press tab it will autocomplete
chmod +x firebuilder
# Done, now you can use it
./firebuilder --help
```

To install and run from the source, you'll want to do this:
```bash
# Follow this guide to install bun: https://bun.sh/docs/installation
git clone https://github.com/explosion-scratch/firebuilder
cd firebuilder
# Install dependencies
pnpm install
pnpm run build:make-vfs

# Run as above
bun cli.js --help
```
